"""import initial

Revision ID: 02e8c4e399e8
Revises: 
Create Date: 2024-11-28 08:59:55.683189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e8c4e399e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etat_inscription', sa.String(), nullable=True),
    sa.Column('rid', sa.String(), nullable=True),
    sa.Column('etat_rid', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('enseigne', sa.String(), nullable=True),
    sa.Column('forme_juridique', sa.String(), nullable=True),
    sa.Column('adresse_physique', sa.String(), nullable=True),
    sa.Column('code_postal_physique', sa.String(), nullable=True),
    sa.Column('ville_physique', sa.String(), nullable=True),
    sa.Column('adresse_postale', sa.String(), nullable=True),
    sa.Column('code_postal_postale', sa.String(), nullable=True),
    sa.Column('ville_postale', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ape', sa.String(), nullable=True),
    sa.Column('code_ape', sa.String(), nullable=True),
    sa.Column('activites_secondaires', sa.String(), nullable=True),
    sa.Column('code_nafa', sa.String(), nullable=True),
    sa.Column('code_nafa_secondaires', sa.String(), nullable=True),
    sa.Column('nb_salaries', sa.Integer(), nullable=True),
    sa.Column('tranche_effectif_salaries', sa.String(), nullable=True),
    sa.Column('taille_structure', sa.String(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('date_radiation', sa.Date(), nullable=True),
    sa.Column('motif_radiation', sa.String(), nullable=True),
    sa.Column('convention_collective', sa.String(), nullable=True),
    sa.Column('situation_entreprise', sa.String(), nullable=True),
    sa.Column('numero_rcs', sa.String(), nullable=True),
    sa.Column('date_immat_rcs', sa.Date(), nullable=True),
    sa.Column('date_radiation_rsc', sa.Date(), nullable=True),
    sa.Column('capital_social', sa.Integer(), nullable=True),
    sa.Column('capital_fixe', sa.Boolean(), nullable=True),
    sa.Column('data_cloture_exercice_comptable', sa.String(), nullable=True),
    sa.Column('duree_personne_morale', sa.String(), nullable=True),
    sa.Column('numero_rm', sa.String(), nullable=True),
    sa.Column('date_immat_rm', sa.Date(), nullable=True),
    sa.Column('date_radiation_rm', sa.Date(), nullable=True),
    sa.Column('numero_rap', sa.String(), nullable=True),
    sa.Column('date_immat_rap', sa.Date(), nullable=True),
    sa.Column('date_radiation_rap', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rid')
    )
    op.create_table('etablissement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_etablissement', sa.String(), nullable=True),
    sa.Column('situation', sa.String(), nullable=True),
    sa.Column('rid', sa.String(), nullable=True),
    sa.Column('et', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('enseigne', sa.String(), nullable=True),
    sa.Column('ape', sa.String(), nullable=True),
    sa.Column('code_ape', sa.String(), nullable=True),
    sa.Column('activites_secondaires', sa.String(), nullable=True),
    sa.Column('code_nafa', sa.String(), nullable=True),
    sa.Column('code_nafa_secondaires', sa.String(), nullable=True),
    sa.Column('adresse_physique', sa.String(), nullable=True),
    sa.Column('code_postal_physique', sa.String(), nullable=True),
    sa.Column('ville_physique', sa.String(), nullable=True),
    sa.Column('adresse_postale', sa.String(), nullable=True),
    sa.Column('code_postal_postale', sa.String(), nullable=True),
    sa.Column('ville_postale', sa.String(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('date_debut_activite', sa.Date(), nullable=True),
    sa.Column('date_fin_activite', sa.Date(), nullable=True),
    sa.Column('convention_collective', sa.String(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bilan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comptes_annuels', sa.String(), nullable=True),
    sa.Column('actes', sa.String(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dirigeant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('date_naissance', sa.String(), nullable=True),
    sa.Column('nationalite', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('titre_cma', sa.String(), nullable=True),
    sa.Column('date_de_fonction_rm', sa.Date(), nullable=True),
    sa.Column('date_de_fonction_ra', sa.Date(), nullable=True),
    sa.Column('situation_matrimoniale', sa.String(), nullable=True),
    sa.Column('maitre_apprentissage', sa.String(), nullable=True),
    sa.Column('qualifie_dans_son_metier', sa.String(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicateurs_financiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('chiffre_affaire', sa.Integer(), nullable=True),
    sa.Column('marge_brute', sa.Integer(), nullable=True),
    sa.Column('excedent_brut_exploitation', sa.Integer(), nullable=True),
    sa.Column('resultat_net', sa.Integer(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicateurs_financiers')
    op.drop_table('dirigeant')
    op.drop_table('bilan')
    op.drop_table('etablissement')
    op.drop_table('entreprise')
    # ### end Alembic commands ###
