"""update dirigeants

Revision ID: 0765dc849dd2
Revises: cd092f6b9a09
Create Date: 2025-01-14 08:52:14.717366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0765dc849dd2'
down_revision: Union[str, None] = 'cd092f6b9a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dirigeant', sa.Column('actif', sa.Boolean(), nullable=True))
    op.add_column('dirigeant', sa.Column('fonction', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('dirigeant', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dirigeant', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dirigeant', 'fonction')
    op.drop_column('dirigeant', 'actif')
    # ### end Alembic commands ###
