"""ajout attribut libelle ape

Revision ID: 2b66a33c4bc4
Revises: c8b17a8f755b
Create Date: 2024-10-30 10:49:59.437397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b66a33c4bc4'
down_revision: Union[str, None] = 'c8b17a8f755b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('ape', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprise', 'ape')
    # ### end Alembic commands ###
