"""correction model entreprise

Revision ID: 3a469696181f
Revises: f80208be5c6c
Create Date: 2024-11-19 08:36:10.167844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a469696181f'
down_revision: Union[str, None] = 'f80208be5c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicateurs_financiers')
    op.drop_table('dirigeant')
    op.add_column('entreprise', sa.Column('etat_inscription', sa.String(), nullable=True))
    op.add_column('entreprise', sa.Column('etat_rid', sa.String(), nullable=True))
    op.add_column('etablissement', sa.Column('ape', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etablissement', 'ape')
    op.drop_column('entreprise', 'etat_rid')
    op.drop_column('entreprise', 'etat_inscription')
    op.create_table('dirigeant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_naissance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nationalite', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adresse', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code_postal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ville', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('titre_cma', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_de_fonction_rm', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_de_fonction_ra', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('situation_matrimoniale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maitre_apprentissage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qualifie_dans_son_metier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name='dirigeant_entreprise_id_fkey'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], name='dirigeant_etablissement_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dirigeant_pkey')
    )
    op.create_table('indicateurs_financiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_cloture', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('chiffre_affaire', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('marge_brute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('excedent_brut_exploitation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resultat_net', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name='indicateurs_financiers_entreprise_id_fkey'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], name='indicateurs_financiers_etablissement_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='indicateurs_financiers_pkey')
    )
    # ### end Alembic commands ###
