"""ajout on delete cascade

Revision ID: 44a1c08b69ed
Revises: 9b522695aa69
Create Date: 2024-12-02 15:57:09.517419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a1c08b69ed'
down_revision: Union[str, None] = '9b522695aa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bilan_etablissement_id_fkey', 'bilan', type_='foreignkey')
    op.drop_constraint('bilan_entreprise_id_fkey', 'bilan', type_='foreignkey')
    op.create_foreign_key(None, 'bilan', 'etablissement', ['etablissement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bilan', 'entreprise', ['entreprise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('dirigeant_etablissement_id_fkey', 'dirigeant', type_='foreignkey')
    op.drop_constraint('dirigeant_entreprise_id_fkey', 'dirigeant', type_='foreignkey')
    op.create_foreign_key(None, 'dirigeant', 'etablissement', ['etablissement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dirigeant', 'entreprise', ['entreprise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('etablissement_entreprise_id_fkey', 'etablissement', type_='foreignkey')
    op.create_foreign_key(None, 'etablissement', 'entreprise', ['entreprise_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('indicateurs_financiers_entreprise_id_fkey', 'indicateurs_financiers', type_='foreignkey')
    op.drop_constraint('indicateurs_financiers_etablissement_id_fkey', 'indicateurs_financiers', type_='foreignkey')
    op.create_foreign_key(None, 'indicateurs_financiers', 'entreprise', ['entreprise_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'indicateurs_financiers', 'etablissement', ['etablissement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indicateurs_financiers', type_='foreignkey')
    op.drop_constraint(None, 'indicateurs_financiers', type_='foreignkey')
    op.create_foreign_key('indicateurs_financiers_etablissement_id_fkey', 'indicateurs_financiers', 'etablissement', ['etablissement_id'], ['id'])
    op.create_foreign_key('indicateurs_financiers_entreprise_id_fkey', 'indicateurs_financiers', 'entreprise', ['entreprise_id'], ['id'])
    op.drop_constraint(None, 'etablissement', type_='foreignkey')
    op.create_foreign_key('etablissement_entreprise_id_fkey', 'etablissement', 'entreprise', ['entreprise_id'], ['id'])
    op.drop_constraint(None, 'dirigeant', type_='foreignkey')
    op.drop_constraint(None, 'dirigeant', type_='foreignkey')
    op.create_foreign_key('dirigeant_entreprise_id_fkey', 'dirigeant', 'entreprise', ['entreprise_id'], ['id'])
    op.create_foreign_key('dirigeant_etablissement_id_fkey', 'dirigeant', 'etablissement', ['etablissement_id'], ['id'])
    op.drop_constraint(None, 'bilan', type_='foreignkey')
    op.drop_constraint(None, 'bilan', type_='foreignkey')
    op.create_foreign_key('bilan_entreprise_id_fkey', 'bilan', 'entreprise', ['entreprise_id'], ['id'])
    op.create_foreign_key('bilan_etablissement_id_fkey', 'bilan', 'etablissement', ['etablissement_id'], ['id'])
    # ### end Alembic commands ###
