"""update correction type duree exercice

Revision ID: 4970fc7626b7
Revises: 51d967d73cd6
Create Date: 2025-01-14 09:53:36.927849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4970fc7626b7'
down_revision: Union[str, None] = '51d967d73cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicateurs_financiers', sa.Column('dureeexercice', sa.Integer(), nullable=True))
    op.drop_column('indicateurs_financiers', 'dureeexcercice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicateurs_financiers', sa.Column('dureeexcercice', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('indicateurs_financiers', 'dureeexercice')
    # ### end Alembic commands ###
