"""update correction type non commandable

Revision ID: 51d967d73cd6
Revises: 8d7e5ce0a015
Create Date: 2025-01-14 09:48:00.957115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d967d73cd6'
down_revision: Union[str, None] = '8d7e5ce0a015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicateurs_financiers', sa.Column('noncommandable', sa.String(), nullable=True))
    op.drop_column('indicateurs_financiers', 'noncommmandable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicateurs_financiers', sa.Column('noncommmandable', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('indicateurs_financiers', 'noncommandable')
    # ### end Alembic commands ###
