"""bilan update

Revision ID: 8d7e5ce0a015
Revises: bcfcf3bbd410
Create Date: 2025-01-14 09:42:53.614956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7e5ce0a015'
down_revision: Union[str, None] = 'bcfcf3bbd410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicateurs_financiers', sa.Column('noncommmandable', sa.String(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('diffusable', sa.String(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('resultat', sa.Float(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('devise', sa.String(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('effectif', sa.String(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('chiffredaffaire', sa.String(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('numerodepot', sa.String(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('dureeexcercice', sa.Integer(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('datedepot', sa.Date(), nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('datecloture', sa.Date(), nullable=True))
    op.drop_column('indicateurs_financiers', 'excedent_brut_exploitation')
    op.drop_column('indicateurs_financiers', 'date_cloture')
    op.drop_column('indicateurs_financiers', 'marge_brute')
    op.drop_column('indicateurs_financiers', 'resultat_net')
    op.drop_column('indicateurs_financiers', 'chiffre_affaire')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicateurs_financiers', sa.Column('chiffre_affaire', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('resultat_net', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('marge_brute', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('date_cloture', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('indicateurs_financiers', sa.Column('excedent_brut_exploitation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('indicateurs_financiers', 'datecloture')
    op.drop_column('indicateurs_financiers', 'datedepot')
    op.drop_column('indicateurs_financiers', 'dureeexcercice')
    op.drop_column('indicateurs_financiers', 'numerodepot')
    op.drop_column('indicateurs_financiers', 'chiffredaffaire')
    op.drop_column('indicateurs_financiers', 'effectif')
    op.drop_column('indicateurs_financiers', 'devise')
    op.drop_column('indicateurs_financiers', 'resultat')
    op.drop_column('indicateurs_financiers', 'diffusable')
    op.drop_column('indicateurs_financiers', 'noncommmandable')
    # ### end Alembic commands ###
