"""sigle au lieu d'enseinge d'une entreprise

Revision ID: 9b522695aa69
Revises: 02e8c4e399e8
Create Date: 2024-12-02 14:46:30.932146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b522695aa69'
down_revision: Union[str, None] = '02e8c4e399e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('sigle', sa.String(), nullable=True))
    op.drop_column('entreprise', 'enseigne')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('enseigne', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entreprise', 'sigle')
    # ### end Alembic commands ###
