"""etablissement: separation rid et ET

Revision ID: 9be149781e11
Revises: 4cefb67d825e
Create Date: 2024-11-27 10:42:31.421810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be149781e11'
down_revision: Union[str, None] = '4cefb67d825e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dirigeant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('nom', sa.String(), nullable=True),
    sa.Column('date_naissance', sa.String(), nullable=True),
    sa.Column('nationalite', sa.String(), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('titre_cma', sa.String(), nullable=True),
    sa.Column('date_de_fonction_rm', sa.Date(), nullable=True),
    sa.Column('date_de_fonction_ra', sa.Date(), nullable=True),
    sa.Column('situation_matrimoniale', sa.String(), nullable=True),
    sa.Column('maitre_apprentissage', sa.String(), nullable=True),
    sa.Column('qualifie_dans_son_metier', sa.String(), nullable=True),
    sa.Column('entreprise_id', sa.Integer(), nullable=True),
    sa.Column('etablissement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('etablissement', sa.Column('rid', sa.String(), nullable=True))
    op.add_column('etablissement', sa.Column('et', sa.String(), nullable=True))
    op.drop_column('etablissement', 'ridet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etablissement', sa.Column('ridet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('etablissement', 'et')
    op.drop_column('etablissement', 'rid')
    op.drop_table('dirigeant')
    # ### end Alembic commands ###
