"""entreprise: correction typo sur type structure

Revision ID: 9cc2f2ce716e
Revises: 0b91d012240b
Create Date: 2025-07-21 08:38:41.076318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc2f2ce716e'
down_revision: Union[str, None] = '0b91d012240b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('type_structure', sa.String(), nullable=True))
    op.drop_column('entreprise', 'type_sctucture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('type_sctucture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entreprise', 'type_structure')
    # ### end Alembic commands ###
