"""ajout situation entreprise

Revision ID: a5bd34aa872e
Revises: 3a469696181f
Create Date: 2024-11-19 08:50:18.776061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bd34aa872e'
down_revision: Union[str, None] = '3a469696181f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entreprise', sa.Column('situation_entreprise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprise', 'situation_entreprise')
    # ### end Alembic commands ###
