"""import initial

Revision ID: ac0a830c5a88
Revises: 
Create Date: 2024-10-21 10:18:19.635524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0a830c5a88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entreprise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entreprise',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sigle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enseigne', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('forme_juridique', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adresse', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code_postal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ville', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entreprise_pkey'),
    sa.UniqueConstraint('rid', name='entreprise_rid_key')
    )
    # ### end Alembic commands ###
