"""nb de salarié en str

Revision ID: f44d59844e5a
Revises: 9ac334f1f550
Create Date: 2025-05-19 14:21:42.246349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44d59844e5a'
down_revision: Union[str, None] = '9ac334f1f550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bilan')
    op.drop_constraint('dirigeant_etablissement_id_fkey', 'dirigeant', type_='foreignkey')
    op.drop_column('dirigeant', 'etablissement_id')
    op.drop_constraint('indicateurs_financiers_etablissement_id_fkey', 'indicateurs_financiers', type_='foreignkey')
    op.drop_column('indicateurs_financiers', 'etablissement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicateurs_financiers', sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('indicateurs_financiers_etablissement_id_fkey', 'indicateurs_financiers', 'etablissement', ['etablissement_id'], ['id'], ondelete='CASCADE')
    op.add_column('dirigeant', sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dirigeant_etablissement_id_fkey', 'dirigeant', 'etablissement', ['etablissement_id'], ['id'], ondelete='CASCADE')
    op.create_table('bilan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comptes_annuels', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('actes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entreprise_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etablissement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name='bilan_entreprise_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissement.id'], name='bilan_etablissement_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='bilan_pkey')
    )
    # ### end Alembic commands ###
